
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;



CREATE TABLE IF NOT EXISTS `departamento` (
  `DEPARTAMENTO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) NOT NULL,
  `DESCRIPCION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`DEPARTAMENTO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;


INSERT INTO `departamento` (`DEPARTAMENTO_ID`, `NOMBRE`, `DESCRIPCION`) VALUES
(2, 'Diseno', 'Departamento de Diseno'),
(4, 'Ingenieria', 'Departamento de Ingenieria');

-- --------------------------------------------------------



CREATE TABLE IF NOT EXISTS `departamento_reunion` (
  `REUNION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEPARTAMENTO_ID` int(11) NOT NULL,
  KEY `FK_REUNION_DEPARTAMENTO_idx` (`DEPARTAMENTO_ID`),
  KEY `FK_DEPARTAMENTOREUNION_REUNION_idx` (`REUNION_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;


INSERT INTO `departamento_reunion` (`REUNION_ID`, `DEPARTAMENTO_ID`) VALUES
(5, 2),
(5, 4);



CREATE TABLE IF NOT EXISTS `empleado` (
  `EMPLEADO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) NOT NULL,
  `APELLIDO` varchar(45) NOT NULL,
  `SALARIO` decimal(11,2) NOT NULL,
  `DEPARTAMENTO_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMPLEADO_ID`),
  KEY `FK_EMPLEADO_DEPARTAMENTO_idx` (`DEPARTAMENTO_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=28 ;



INSERT INTO `empleado` (`EMPLEADO_ID`, `NOMBRE`, `APELLIDO`, `SALARIO`, `DEPARTAMENTO_ID`) VALUES
(25, 'Jose', 'Diaz', 12000.00, 4),
(26, 'Miryan', 'Ramirez', 10000.00, 2);

-- --------------------------------------------------------


CREATE TABLE IF NOT EXISTS `reunion` (
  `REUNION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) NOT NULL,
  `DESCRIPCION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`REUNION_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;



INSERT INTO `reunion` (`REUNION_ID`, `NOMBRE`, `DESCRIPCION`) VALUES
(5, 'Revision', 'Revision Semanal');


ALTER TABLE `departamento_reunion`
  ADD CONSTRAINT `FK_DEPARTAMENTOREUNION_DEPARTAMENTO` FOREIGN KEY (`DEPARTAMENTO_ID`) REFERENCES `departamento` (`DEPARTAMENTO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_DEPARTAMENTOREUNION_REUNION` FOREIGN KEY (`REUNION_ID`) REFERENCES `reunion` (`REUNION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE `empleado`
  ADD CONSTRAINT `FK_EMPLEADO_DEPARTAMENTO` FOREIGN KEY (`DEPARTAMENTO_ID`) REFERENCES `departamento` (`DEPARTAMENTO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
